services:
  db:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: rma_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_schema:/docker-entrypoint-initdb.d

volumes:
  pgdata: